# PickleSwear config.yml
disabledwords:
  - igniss
  - justanotherone
  - thirdword
  - ilikenuts
messages:
  antiswear: §4Stop swearing you pickle!
  noperm: §cNo permission :(
  reload: §aRick the Pickle reloaded the configuration!
announce-messages:
  first: "§cPlayer §7%player% §csaid bad word!"
  second: "§cCensored word: §7%word%"
  third: "§cFull sentence: §7%sentence%"
