# Add here words that should be forbidden
disabledwords:
  - igniss
  - justanotherone
  - thirdword
  - ilikenuts

# Messages
messages:
# If player swears
  antiswear: §4Stop swearing you pickle!
# If player doesnt have permission to reload configuration
  noperm: §cNo permission :(
  reload: §aRick the Pickle reloaded the configuration!