name: PickleSwear
author: iGniSsak
version: "1.2.7"
main: net.iGniSsak.PickleSwear.PickleSwear
commands:
  pickleswear:
    description: Reload configuration!
    usage: /<command>
permission:
  pickleswear.reload:
    description: Access to reload configuration
    default: op
  pickleswear.see:
    description: Can see players who swears
    default: op
  pickleswear.bypass:
    description: Plugin doesnt affect player's messages
    default: op