name: PickleSwear
author: iGniSsak
version: "1.2.1"
main: net.iGniSsak.PickleSwear.Main
commands:
  picklereload:
    description: Reload configuration!
    usage: /<command>
permission:
  pickleswear.reload:
    description: Access to reload configuration
    default: op
  pickleswear.see:
    description: Can see players who swears
    default: op